/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import { Inter, Montserrat, Roboto_Mono } from 'next/font/google';
import "./globals.css";
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });
const montserrat = Montserrat({ subsets: ['latin'] });
const robotoMono = Roboto_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Bitcoin Trading Analysis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Bitcoin Trading Analysis</title>
      </head>
      <body className={inter.className}>
        {/* Kakao 광고 (상단) */}
        <div className="flex justify-center">
          <ins 
            className="kakao_ad_area" 
            style={{ display: "none" }}
            data-ad-unit="DAN-0A1Dxif5Rgz57Nwg"
            data-ad-width="320"
            data-ad-height="100"
          />
          <Script
            src="//t1.daumcdn.net/kas/static/ba.min.js"
            async
          />
        </div>

        {children}

        {/* Kakao 광고 (하단) */}
        <div className="flex justify-center mt-8">
          <ins 
            className="kakao_ad_area" 
            style={{ display: "block" }}
            data-ad-unit="DAN-6jUyeCB09Hw8CGmH"
            data-ad-width="300"
            data-ad-height="250"
          />
          <Script
            src="//t1.daumcdn.net/kas/static/ba.min.js"
            async
          />
        </div>
      </body>
    </html>
  );
}
