name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    steps:
      - uses: actions/checkout@v2
      
      # 더 자세한 디버그 정보 추가
      - name: Debug env
        run: |
          echo "Secret exists: ${{ secrets.OPENAI_API_KEY != '' }}"
          echo "Secret first chars: ${OPENAI_API_KEY:0:5}..."
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build 